### ISSUE TITLE
有没有生成的问卷页面

### ISSUE THREAD

**Issue by 1104049235** [luyilin/vue-google-form#1]
表单编辑完怎么获取问卷页面？

**Comment by luyilin** [comment]
![image](https://user-images.githubusercontent.com/12069729/84654396-ad183000-af41-11ea-98a8-3d980dba018b.png)
看了一下木有写保存后的代码，只是半成品，可以自己添加哈

**Comment by 1104049235** [comment]
我是后端，vue 也就看的懂，写不出来呀，唉  心态崩了！！

**Comment by luyilin** [comment]
问卷的数据结构已经有了，渲染一下就可以了，可以看下vue的写法，很快就能掌握的！

**Comment by 1104049235** [comment]
恩好  我看看怎么渲染  直接在savefn()里保存json格式数据  然后渲染吗？

**Comment by luyilin** [comment]
前端展示的话不用保存，直接渲染就可以了，如果想保存问卷数据的话需要服务端保存一下

**Comment by 1104049235** [comment]
渲染  表示不会  头晕了，跟那个可视化表单编辑  然后渲染表单那个一样吗？我搜索下看看 ！

**Comment by 1104049235** [comment]
![2020-06-16 11-39-49 的屏幕截图](https://user-images.githubusercontent.com/30166746/84729380-22c5df80-afc6-11ea-8737-f1dd6a383730.png)
这样的数据杂渲染对应input textarea 这些就行是把？

**Comment by luyilin** [comment]
对的 渲染展示就可以了

**Comment by 1104049235** [comment]
谢拉  不会我在问你哈 ### ！！！感谢！哈哈哈

**Comment by 1104049235** [comment]
> 对的 渲染展示就可以了

你好  为啥我引入我项目后样式不见了  我是小白！！

**Comment by luyilin** [comment]
vue 文件里有引用css文件吗？引用scss文件的话，需要加一些依赖
![image](https://user-images.githubusercontent.com/12069729/86090389-94c91900-badc-11ea-8ef2-7719802a86bd.png)

**Comment by 1104049235** [comment]
恩恩  引入了  多谢多谢！！

**Comment by 1104049235** [comment]
引入后发现全局生效了 ，怎么让单独vue文件内生效阿？还得问问你

**Comment by luyilin** [comment]
加个 scoped ？Google一下哈～

**Comment by 1104049235** [comment]
搜索了，但是加完这个后自身页面有些也出问题了，我在调调看





------------------ 原始邮件 ------------------
发件人: 怡潼 <notifications@github.com&gt;
发送时间: 2020年6月30日 14:52
收件人: luyilin/vue-google-form <vue-google-form@noreply.github.com&gt;
抄送: 1104049235 <1104049235@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[luyilin/vue-google-form] 有没有生成的问卷页面 (#1)





 
加个 scoped ？Google一下哈～

**Comment by 1104049235** [comment]
这个自动换行我要怎么引入呀实在搜索不到

------------------ 原始邮件 ------------------
发件人: 怡潼 <notifications@github.com&gt;
发送时间: 2020年6月30日 14:52
收件人: luyilin/vue-google-form <vue-google-form@noreply.github.com&gt;
抄送: 1104049235 <1104049235@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[luyilin/vue-google-form] 有没有生成的问卷页面 (#1)





 
加个 scoped ？Google一下哈～

**Comment by luyilin** [comment]
什么自动换行啊？

**Comment by 1104049235** [comment]
嘿嘿图片没发出去，就是绑定了个@input="$autoText($event)" 这个一直报错

**Comment by 1104049235** [comment]
不太懂这个是干啥的

**Comment by 1104049235** [comment]
好了  我在main 引入了
